config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :images
  root 'images#index'

  get '/upload', to: "images#fileupload"
  post '/upload', to: "images#upload"
  get '/tags', to: "tags#index"
  get '/play/:id', to: "images#play"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :url, presence: true

  acts_as_taggable_on :tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_ownership, only: [:show, :edit, :update, :destroy]

  def index
    @images = current_user.images.where(hidden: false)
    @sort = params[:sort]
    case @sort
    when "new"
      @images = @images.order(created_at: :desc)
    when "favorite"
      @images = @images.where(favorite: true)
    when "hidden"
      @images = current_user.images.where(hidden: true)
    else
      @images = @images.order("RANDOM()")
    end
    @title_query = params[:title_query]
    @tag_query = params[:tag_query]

    if @title_query && @title_query != ""
      @images = @images.where("title LIKE ?", "%#{@title_query}%")
    end

    if @tag_query && @tag_query != ""
      case params[:qtype]
      when "any"
        @images = @images.tagged_with(@tag_query, :any => true)
      when "exact"
        @images = @images.tagged_with(@tag_query, :match_all => true)
      when "exclude"
        @images = @images.tagged_with(@tag_query, :exclude => true)
      else
        @images = @images.tagged_with(@tag_query)
      end
    end

    @photos = @images.where(mediatype: "image")
    @videos = @images.where(mediatype: "video")
    @links = @images.where(mediatype: "link")
  end

  def show
    @image = Image.find(params[:id])
  end

  def play # just for videos
    @video = Image.find(params[:id])
  end

  def new
    @image = current_user.images.new
  end

  def create
    @image = current_user.images.new(image_params)
    @image.tag_list.add("favorite") if @image.favorite

    if @image.save
      redirect_to @image
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])


    if @image.update(image_params)
      if @image.favorite
        @image.tag_list.add("favorite")
      else
        @image.tag_list.remove("favorite")
      end
      @image.save
      redirect_to images_path # edit_image_path(params[:id].to_i + 1)
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    redirect_to images_path
  end

  def fileupload

  end

  def upload
    if params[:images]
      uploaded_file = params[:images]
      table = CSV.parse(uploaded_file.read)

      table.each do |row|
        next if row[0] == "id" # header row

        if !Image.where(url: row[1]).exists?
          image = current_user.images.new(url: row[1], title: row[2], desc: row[3], favorite: row[4], mediatype: row[8])
          image.save
        end
      end
    end

    if params[:tags] && params[:taggings]
      tags = CSV.parse(params[:tags].read)
      taggings = CSV.parse(params[:taggings].read)

      taggings.each do |row|
        next if row[0] == "id" # header row

        tag_name = tags[row[1].to_i][1] # get name column of tag record with id equal to tag_id (DANGEROUS: assumes tags are in order by id)
        tagged = Image.find(row[3])
        tagged.tag_list.add(tag_name)
        tagged.save
      end
    end

    redirect_to images_path
  end

  private
    def image_params
      params.require(:image).permit(:title, :url, :desc, :mediatype, :favorite, :tag_list, :hidden)
    end
    def verify_ownership
      if Image.find(params[:id]).user_id != current_user.id
        redirect_to images_path
      end
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all.order(id: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/images/edit.html.erb
<%= link_to "All images", images_path %><br>
<%= link_to "This image", @image %>

<h1><%= @image.title %></h1>

<%= form_with model: @image, class: "new-image-form" do |f| %>
  <div class="field">
    <%= f.text_field :url, placeholder: "URL" %>
  </div>

  <div class="field">
    <%= f.text_field :title, placeholder: "Title" %>
  </div>

  <div class="field">
    <%= f.label :desc, "Comments (optional)" %><br>
    <%= f.text_area :desc, placeholder: "Any additional comments about this image" %>
  </div>

  <div class="field">
    <%= f.check_box :favorite %>
    <%= f.label :favorite, "Favorite?" %>
  </div>

  <div class="field">
    <%= f.check_box :hidden %>
    <%= f.label :hidden, "Hide" %>
  </div>

  <div class="field">
    <%= f.label :mediatype, "Media type" %><br>
    <%= f.select(:mediatype, [['image','image'],['video','video'],['link','link']]) %><br>
  </div>

  <div class="field">
    <h3>Categories</h3>
    <%= f.text_area :tag_list %>
  </div>

  <%= f.submit "Update image" %>

  <%= link_to "Delete image", image_path(@image.id), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>

app/views/images/fileupload.html.erb
<h1>Upload CSV data</h1>

<%= form_with url: "/upload", multipart: true do |f| %>
  <%= f.label :images %>
  <%= f.file_field :images %><br>

  <%= f.label :tags %>
  <%= f.file_field :tags %><br>

  <%= f.label :taggings %>
  <%= f.file_field :taggings %><br>
  <br>
  <%= f.submit "Upload CSV" %>
<% end %>

app/views/images/index.html.erb
<h1>Here are all your images lol</h1>

<%= @images.size %> total:
<ul>
  <li><%= pluralize(@photos.size, 'photo') %></li>
  <li><%= pluralize(@videos.size, 'video') %></li>
  <li><%= pluralize(@links.size, 'link') %></li>
</ul>

<%= link_to "Upload CSV data", "/upload" %><br><br>

<%= link_to "Add image", new_image_path %><br><br>

<%= form_with url: images_path, method: :get do |f| %>
  <%= f.label :tag_query, "Search by tag(s):" %>
  <%= f.text_field :tag_query %>
  <%= f.select(:qtype, ['any','exact','exclude']) %>
  <%= link_to "See all tags", "/tags" %><br>

  <%= f.label :title_query, "Search by title:" %>
  <%= f.text_field :title_query %><br>

  <%= f.submit "Search" %>
<% end %>

<% if @tag_query && @tag_query != "" %>
  <h3>Displaying images with tag(s): <%= params[:tag_query] %></h3>
<% end %>
<% if @title_query && @title_query != "" %>
  <h3>Displaying images with title containing: <%= params[:title_query] %></h3>
<% end %>
<% if @tag_query || @title_query %>
  <%= link_to "Show all", images_path %>
<% end %>

<div class="page-blur">
  <div class="show-image"></div>
</div>

<div class="images-index">
  <% if @photos.any? %>
    <% @photos.each do |photo| %>
      <div class="image-wrapper" id="image-wrapper-<%= photo.id %>">
        <%= link_to image_tag(photo.url, title: photo.title), photo, remote: true %>
      </div>
    <% end %>
  <% end %>
</div>

<div class="videos-container">
  <div class="videos-index">
    <% if @videos.any? %>
      <% @videos.each do |video| %>
        <%= link_to video.title, "/play/#{video.id}", remote: true %>
      <% end %>
    <% end %>
  </div>
  <div class="video-player">
    Select a video on the left!
  </div>
</div>

<div class="links-index">
  <% if @links.any? %>
    <% @links.each do |link| %>
      <%= link_to link.title, link.url, target: "_blank" %> (<%= link_to "edit", edit_image_path(link.id) %>)<br>
    <% end %>
  <% end %>
</div>

app/views/images/new.html.erb
<h1>Add image</h1>

<%= form_with model: @image, class: "new-image-form" do |f| %>
  <div class="field">
    <%= f.text_field :url, placeholder: "URL" %>
  </div>

  <div class="field">
    <%= f.text_field :title, placeholder: "Title" %>
  </div>

  <div class="field">
    <%= f.label :desc, "Comments (optional)" %><br>
    <%= f.text_area :desc, placeholder: "Any additional comments about this image" %>
  </div>

  <div class="field">
    <%= f.check_box :favorite %>
    <%= f.label :favorite, "Favorite?" %>
  </div>

  <div class="field">
    <%= f.label :mediatype, "Media type" %><br>
    <%= f.select(:mediatype, ['image','video','link']) %><br>
  </div>

  <div class="field">
    <h3>Categories</h3>
    <%= f.text_area :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit "Add image" %>
  </div>
<% end %>

app/views/images/play.js.erb
$('.video-player').html('<div class="video-view-links"><%= link_to "Edit", edit_image_path(@video) %></div><video src="<%= @video.url %>" controls autoplay>');

$('.clear-player-btn').click(() => {
  $('.video-player').html("Select a video on the left!");
})

app/views/images/show.html.erb
<body style="background-color:#0e0e0e;padding:0;margin:0;">
  <%= link_to "edit", edit_image_path(@image.id), class: "ahidden" %>
  <% if @image.mediatype == "image" %>
    <%= link_to image_tag(@image.url, class: "fullsize"), @image.url %>
  <% elsif @image.mediatype == "video" %>
    <%= link_to video_tag(@image.url, controls: true, class: "fullsize"), @image.url %>
  <% elsif @image.mediatype == "link" %>
    <%= link_to @image.url %>
  <% end %>
</body>

app/views/images/show.js.erb
$('.page-blur, .show-image').css({
  display: "flex"
});
$('.page-clickable').css('display','block');

$('.show-image').html('<div class="image-view-links"><%= link_to "Edit", edit_image_path(@image) %> | <%= link_to "Show", @image %></div><img src="<%= @image.url %>">');

$('.show-image').click(() => {
  $('.page-blur, .show-image, .page-clickable').css("display","none");
}).children().on("click", function (e) {
    e.stopPropagation();
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mediaorganizer2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <%= current_user.email %> | <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Number of images</th>
  </tr>
  <% @tags.each do |tag| %>
    <tr>
      <td><%= link_to tag.name, images_path(:tag_query => tag.name) %></td>
      <td><%= tag.taggings_count %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to "All images", images_path %>